# Generated by Django 3.0.3 on 2021-08-19 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=256, verbose_name='企业名称')),
                ('tax_number', models.CharField(default='', max_length=256, verbose_name='企业税号')),
                ('tan_yan_url', models.CharField(default='', max_length=256, verbose_name='企业名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('data_flag', models.IntegerField(default=0, verbose_name='数据标记')),
            ],
            options={
                'verbose_name': '企业信息主表',
                'verbose_name_plural': '企业信息主表',
            },
        ),
    ]
