# Generated by Django 3.0.3 on 2021-08-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_info',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='企业地址'),
        ),
        migrations.AlterField(
            model_name='company_info',
            name='tan_yan_url',
            field=models.CharField(default='', max_length=256, verbose_name='企业详情url'),
        ),
    ]
